VideoGameLibrary/Models/VideoGame.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace VideoGameLibrary.Models
{
    public class VideoGame
    {
        public int? Id { get; set; }
        public string OwnerId { get; set; }

        [MaxLength(500)]
        public string ImgSrc { get; set; }

        [Required(ErrorMessage = "Title cannot be empty")]
        [MaxLength(500)]
        public string Title { get; set; }

        [Required(ErrorMessage = "Genre cannot be empty")]
        [MaxLength(500)]
        public string Genre { get; set; }

        [Required(ErrorMessage = "Year cannot be empty")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Rating cannot be empty")]
        [MaxLength(500)]
        public string EsrbRating { get; set; }

        [Required(ErrorMessage = "Platform cannot be empty")]
        [MaxLength(500)]
        public string Platform { get; set; }

        [MaxLength(500)]
        public string LoanedTo { get; set; }
        public DateTime LoanDate { get; set; }


        public VideoGame() {}
        public VideoGame(string imgSrc, string title, string genre, int year, string esrbRating, string platform)
        {
            ImgSrc = imgSrc;
            Title = title;
            Genre = genre;
            Year = year;
            EsrbRating = esrbRating;
            Platform = platform;

        }
        public VideoGame(int id, string imgSrc, string title, string genre, int year, string esrbRating, string platform, string ownerId)
        {
            Id = id;
            ImgSrc = imgSrc;
            Title = title;
            Genre = genre;
            Year = year;
            EsrbRating = esrbRating;
            Platform = platform;
            OwnerId = ownerId;
  
        }
        public VideoGame(int id, string imgSrc, string title, string genre, int year, string esrbRating, string platform, string loanedTo, DateTime loanDate, string ownerId ) 
        {
            Id = id;
            ImgSrc = imgSrc;
            Title = title;
            Genre = genre;
            Year = year;
            EsrbRating = esrbRating;
            Platform = platform;
            LoanedTo = loanedTo;
            LoanDate = loanDate;
            OwnerId = ownerId;
        }
        public VideoGame(string imgSrc, string title, string genre, int year, string esrbRating, string platform, string loanedTo, DateTime loanDate)
        {
            ImgSrc = imgSrc;
            Title = title;
            Genre = genre;
            Year = year;
            EsrbRating = esrbRating;
            Platform = platform;
            LoanedTo = loanedTo;
            LoanDate = loanDate;
        }
    }
}

VideoGameLibrary/Controllers/CollectionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using VideoGameLibrary.Data;
using VideoGameLibrary.Interfaces;
using VideoGameLibrary.Models;

namespace VideoGameLibrary.Controllers
{
    public class CollectionController : Controller
    {
        
        IDataAccessLayer dataAccessLayer;

        public CollectionController(IDataAccessLayer dal)
        {
            dataAccessLayer = dal;
            //Uncomment and run to quickly add default games to db
            //((VideoGameDBDal)dataAccessLayer).AddDefaultGames();
        }

        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {
            return View(dataAccessLayer.GetCollection(User.FindFirstValue(ClaimTypes.NameIdentifier)));
        }
        [HttpPost]
        public IActionResult Index(string titleFilterInput, string btnradioRating, string filterPlatform, string filterGenre)
        {
            Console.WriteLine($"{titleFilterInput}, {btnradioRating}, {filterPlatform}, {filterGenre}");
            var filterCollection = dataAccessLayer.FilterCollection(User.FindFirstValue(ClaimTypes.NameIdentifier), filterGenre, filterPlatform, btnradioRating);
            Console.WriteLine("FilterCollection: " + filterCollection.Count());
            var searchCollection = dataAccessLayer.SearchForGames(User.FindFirstValue(ClaimTypes.NameIdentifier), titleFilterInput);
            Console.WriteLine("SearchCollection: " + searchCollection.Count());
            List<VideoGame> finalCollection = new List<VideoGame>();
            foreach(VideoGame searchResult in searchCollection)
            {
                foreach(VideoGame filterResult in filterCollection)
                {
                    if (searchResult == filterResult)
                    {
                        finalCollection.Add(filterResult);
                        break;
                    }
                }
            }

            return View(finalCollection);
        }

        public IActionResult ReturnGame(int gameID)
        {
            dataAccessLayer.ReturnGame(gameID);
            return Redirect("~/Collection/Index");
        }

        [HttpPost]
        public IActionResult RentGame()
        {

            int gameID = int.Parse(Request.Form["gameid"]);
            string loanedTo = Request.Form["renterName"].ToString();
            dataAccessLayer.RentGame(gameID, loanedTo);

            return Redirect("~/Collection/Index");
        }


        [HttpPost]
        public IActionResult DeleteGame()
        {
            int gameID = int.Parse(Request.Form["gameid"]);
            dataAccessLayer.DeleteGame(gameID);
            return Redirect("~/Collection/Index");

        }

        public IActionResult GameForm()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddGameAsync(VideoGame game)
        {
            if (ModelState.IsValid)
            {
                if (game.Id == -1)
                {
                    game.Id = null;
                }
                game.OwnerId = User.FindFirstValue(ClaimTypes.NameIdentifier);

                //Test if image is real. If it is not, use placeholder image
                try
                {
                    using var client = new HttpClient();
                    var result = await client.GetAsync(game.ImgSrc);
                    //Console.WriteLine(result.Content.Headers.ContentType);
                    if(!result.Content.Headers.ContentType.ToString().Contains("image")) game.ImgSrc = "/img/noImage.png";
                } catch(Exception e)
                {
                    //Link does not lead anywhere
                    //set default image
                    game.ImgSrc = "/img/noImage.png";
                }

                dataAccessLayer.AddGame(game);
                return Redirect("~/Collection/Index");
            }
            return View("GameForm");
        }



    }
}

VideoGameLibrary/Views/Collection/GameForm.cshtml
@model VideoGame
@{
}


<div>
    <h2>Add Video Game</h2>
    <form asp-controller="Collection" asp-action="AddGame" method="post" id="addGameForm">
        <input value="-1" asp-for="Id" type="hidden" />
        <div class="form-group">
            <label for="Title">Title:</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="err-msg"></span>
        </div>
        <div class="form-group">
            <label for="Year">Year:</label>
            <input asp-for="Year" class="form-control" />
            <span asp-validation-for="Year" class="err-msg"></span>
        </div>
        <div class="form-group">
            <label for="Genre">Genre:</label>
            <input asp-for="Genre" class="form-control" />
            <span asp-validation-for="Genre" class="err-msg"></span>
        </div>
        <div class="form-group spacing">
            <label for="ImgSrc">External Image Link:</label>
            <input asp-for="ImgSrc" class="form-control" />
        </div>
        <div class="form-group spacing">
            <label for="EsrbRating">ESRB Rating:</label>
            <select asp-for="EsrbRating" class="form-select">
                <option value="E">E</option>
                <option value="T">T</option>
                <option value="M">M</option>
                <option value="A">A</option>
                <option value="RP">RP</option>
            </select>
        </div>
        <div class="form-group spacing">
            <label for="Platform">Platform:</label>
            <select asp-for="Platform" class="form-select">
                <option value="Nintendo Switch">Nintendo Switch</option>
                <option value="Nintendo Wii">Nintendo Wii</option>
                <option value="Playstation 2">Playstation 2</option>
                <option value="Playstation 3">Playstation 3</option>
                <option value="Playstation 4">Playstation 4</option>
                <option value="Playstation 5">Playstation 5</option>
                <option value="Steam">Steam</option>
                <option value="Xbox 360">Xbox 360</option>
                <option value="Xbox 1">Xbox 1</option>
            </select>
        </div>
        <button type="submit" class="btn btn-purple btn-center">Add Game</button>
    </form>
</div>

VideoGameLibrary/Views/Collection/Index.cshtml
@model IEnumerable<VideoGame>
@{
    ViewData["Title"] = "Game Collection";
}

<div class="collection-body">
    <div class="header-div">
        <h2 class="text-center">Collection (@Model.Count())</h2>
        <button class="btn btn-purple" id="addGameBtn" onclick="location.href='@Url.Action("GameForm","Collection")'">+</button>
    </div>

    <form class="filter-section row justify-content-center" asp-controller="Collection" asp-action="Index" method="post">
        <input type="text" id="titleFilterInput" placeholder="Search by Title" name="titleFilterInput" />
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="filterDropdownMenu" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="~/img/gear.svg" />
            </button>
            <div class="dropdown-menu keep-open p-4" id="filterMenu" aria-labelledby="filterDropdownMenu">
                <div class="mb-3">
                    <label for="filterRating" class="form-label">ESRB Rating</label>
                    <div class="btn-group" role="group" aria-label="Basic radio toggle button group" id="filterRating">
                        <input type="radio" class="btn-check" name="btnradioRating" value="" id="btnradioRating1" autocomplete="off" checked>
                        <label class="btn btn-outline-purple" for="btnradioRating1">All</label>

                        <input type="radio" class="btn-check" name="btnradioRating" value="E" id="btnradioRating2" autocomplete="off">
                        <label class="btn btn-outline-purple" for="btnradioRating2">E</label>

                        <input type="radio" class="btn-check" name="btnradioRating" value="T" id="btnradioRating3" autocomplete="off">
                        <label class="btn btn-outline-purple" for="btnradioRating3">T</label>

                        <input type="radio" class="btn-check" name="btnradioRating" value="M" id="btnradioRating4" autocomplete="off">
                        <label class="btn btn-outline-purple" for="btnradioRating4">M</label>

                        <input type="radio" class="btn-check" name="btnradioRating" value="A" id="btnradioRating5" autocomplete="off">
                        <label class="btn btn-outline-purple" for="btnradioRating5">A</label>

                        <input type="radio" class="btn-check" name="btnradioRating" value="RP" id="btnradioRating6" autocomplete="off">
                        <label class="btn btn-outline-purple" for="btnradioRating6">RP</label>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="filterPlatform" class="form-label">Platform</label>
                    <input list="platforms" id="filterPlatform" name="filterPlatform">
                    <datalist id="platforms">
                        <option value="Nintendo Switch" />
                        <option value="Nintendo Wii" />
                        <option value="Playstation 2" />
                        <option value="Playstation 3" />
                        <option value="Playstation 4" />
                        <option value="Playstation 5" />
                        <option value="Steam" />
                        <option value="Xbox 360" />
                        <option value="Xbox 1" />
                    </datalist>
                </div>
                <div class="mb-3">
                    <label for="filterGenre" class="form-label">Genre</label>
                    <input list="genres" id="filterGenre" name="filterGenre">
                    <datalist id="genres">
                        <option value="Action" />
                        <option value="Adventure" />
                        <option value="FPS" />
                        <option value="Puzzle" />
                        <option value="Platformer" />
                        <option value="Indie" />
                        <option value="Roguelike" />
                        <option value="Horror" />
                    </datalist>
                </div>
            </div>
        </div>
        <button class="btn btn-purple" id="searchBtn" type="submit">Search</button>
        <button class="btn btn-purple" id="resetFiltersBtn" onclick="location.href='@Url.Action("Index","Collection")'">Reset</button>

    </form>

    <div class="videogame-collection">
        @if (Model == null)
        {
            <h1>No Games Provided</h1>
        }
        else
        {
            foreach (var videogame in Model)
            {
                <partial name="_VideoGame.cshtml" for="@videogame" />
            }
        }
    </div>





    <div class="modal fade" id="rentModal" tabindex="-1" aria-labelledby="rentModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="rentModalLabel">Rent A Game</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        
                    </button>
                </div>
                <form asp-controller="Collection" asp-action="RentGame" method="post">
                    <div class="modal-body">
                        <h5 class="modal-game-title"></h5>
                        <p>Please enter your name to rent this game:</p>
                        <input type="hidden" name="gameid" id="gameidRent" />
                        <input type="text" id="renterName" name="renterName" placeholder="Name" required />

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-purple">Rent</button>
                    </div>
                </form>
            </div>
        </div>
    </div>



    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete Game</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        
                    </button>
                </div>
                <form asp-controller="Collection" asp-action="DeleteGame" method="post">
                    <div class="modal-body">
                        <p>Are you sure you want to delete this game?</p>
                        <input type="hidden" name="gameid" id="gameidDelete" />
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


    


    </div>

VideoGameLibrary/Views/Collection/_VideoGame.cshtml
@model VideoGame 
@{
}

@if (Model == null)
{
    <h1>No Game Provided</h1>
}
else
{
    
    <div class='@( (Model.LoanDate != null && !string.IsNullOrEmpty(Model.LoanedTo)) ? "videogame-container rented" : "videogame-container")' >
        <div class="videogame-info">
            <div class="close-btn" data-bs-toggle="modal" data-bs-target="#deleteModal" data-game="@Model.Title" data-gameID="@Model.Id">&#10005;</div>
            <div class="text-center">
                <h3>@Model.Title</h3>
                <p>@Model.Year</p>

                <table>
                    <tbody>
                        <tr>
                            <td>Genre:</td>
                            <td>@Model.Genre</td>
                        </tr>
                        <tr>
                            <td>Platform:</td>
                            <td>@Model.Platform</td>
                        </tr>
                        <tr>
                            <td>Rating:</td>
                            <td>@Model.EsrbRating</td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="loan-section">
                @if (Model.LoanDate != null && !string.IsNullOrEmpty(Model.LoanedTo))
                {

                    <h5>Loaned By:</h5>
                    <div>
                        <p>@Model.LoanedTo</p>
                        <p>@Model.LoanDate.ToShortDateString()</p>
                    </div>
                    <a class="btn btn-purple btn-center link-purple" asp-controller="Collection" asp-action="ReturnGame" asp-route-gameID="@Model.Id">Return</a>

                }
                else
                {
                    <button class="btn btn-purple btn-center" data-bs-toggle="modal" data-bs-target="#rentModal" data-game="@Model.Title" data-gameID="@Model.Id">Rent Game</button>
                }
            </div>
        </div>
    <img draggable="false" src="@Model.ImgSrc" placeholder="@Model.Title" />
</div>
}